# Generated by Django 6.0.4 on 2026-04-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_edda_library', '0002_lore_excerpt_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='lore',
            options={'ordering': ['title']},
        ),
    ]
