# Generated by Django 6.0.4 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_edda_library', '0003_alter_comment_options_alter_lore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lore',
            name='is_deletion_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lore',
            name='excerpt',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
