# Generated by Django 6.0.4 on 2026-05-08 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_edda_library', '0004_lore_is_deletion_pending_alter_lore_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lore',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
