# Generated by Django 6.0.4 on 2026-05-13 16:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_edda_library', '0005_lore_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
