# Generated by Django 6.0.4 on 2026-05-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_edda_library', '0006_alter_lore_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
