# Generated by Django 6.0.4 on 2026-04-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_entity_archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['entity_name']},
        ),
    ]
