# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_entity_archive', '0002_alter_entity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='entity_name',
            new_name='name',
        ),
    ]
