# Generated by Django 6.0.4 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_entity_archive', '0003_alter_entity_options_rename_entity_name_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_deletion_pending',
            field=models.BooleanField(default=False),
        ),
    ]
