# Generated by Django 6.0.4 on 2026-05-08 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_entity_archive', '0004_entity_is_deletion_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
